[pytest]
pythonpath = . src
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
env = 
    ENVIRONMENT=test
    DB_HOST=localhost
    DB_PORT=5432
    DB_USER=postgres
    DB_PASSWORD=musleno
    DB_NAME=LMS_TEST
    JWT_SECRET_KEY=323b9d0ab20d8983e7b9fb1e6516fda70b9ca2fa6e03eea7011ca5646aaa6d34
    REDIS_HOST=localhost
    REDIS_PORT=6379
    REDIS_PASSWORD=
    REDIS_DB=1
