"""increase book's tables fields size

Revision ID: 153d06e5a6a1
Revises: e2698c73d67c
Create Date: 2026-05-19 14:24:27.844405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '153d06e5a6a1'
down_revision: Union[str, Sequence[str], None] = 'e2698c73d67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "title",
        existing_type=sa.String(length=50),
        type_=sa.String(length=60),
    )
    op.alter_column(
        "books",
        "author",
        existing_type=sa.String(length=30),
        type_=sa.String(length=60),
    )
    op.alter_column(
        "books",
        "description",
        existing_type=sa.String(length=100),
        type_=sa.String(length=500),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "title",
        existing_type=sa.String(length=60),
        type_=sa.String(length=50),
    )
    op.alter_column(
        "books",
        "author",
        existing_type=sa.String(length=60),
        type_=sa.String(length=30),
    )
    op.alter_column(
        "books",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.String(length=100),
    )
    # ### end Alembic commands ###
