"""...

Revision ID: 248f8633b07a
Revises: 3dc121d38c8a
Create Date: 2026-05-31 21:06:37.516132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "248f8633b07a"
down_revision: Union[str, Sequence[str], None] = "3dc121d38c8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("inventories_added_by_fkey"), "inventories", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("inventories_book_id_fkey"), "inventories", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "inventories", "users", ["added_by"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "inventories", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "loans",
        "returned_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "loans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_activation",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_activation",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("users_activation_user_id_fkey"), "users_activation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "users_activation", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "users_sessions",
        sa.Column("pending_new_email", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "users_sessions",
        sa.Column("email_change_code_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "users_sessions",
        sa.Column(
            "email_change_code_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.alter_column(
        "users_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_sessions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("users_sessions_user_id_fkey"), "users_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "users_sessions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_sessions_user_id_fkey"),
        "users_sessions",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "users_sessions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users_sessions", "email_change_code_expires_at")
    op.drop_column("users_sessions", "email_change_code_hash")
    op.drop_column("users_sessions", "pending_new_email")
    op.drop_constraint(None, "users_activation", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_activation_user_id_fkey"),
        "users_activation",
        "users",
        ["user_id"],
        ["id"],
    )
    op.alter_column(
        "users_activation",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_activation",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "returned_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "inventories", type_="foreignkey")
    op.drop_constraint(None, "inventories", type_="foreignkey")
    op.create_foreign_key(
        op.f("inventories_book_id_fkey"), "inventories", "books", ["book_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("inventories_added_by_fkey"), "inventories", "users", ["added_by"], ["id"]
    )
    # ### end Alembic commands ###
