"""Add account activation fields to User

Revision ID: 2d1615f5ad09
Revises: 0884898b01e3
Create Date: 2026-04-21 11:33:15.801275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1615f5ad09'
down_revision: Union[str, Sequence[str], None] = '0884898b01e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_activation_code_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('account_activation_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_activation_code_expires_at')
    op.drop_column('users', 'account_activation_code_hash')
    # ### end Alembic commands ###
