"""Add reset password fields to users_sessions

Revision ID: 3dc121d38c8a
Revises: 153d06e5a6a1
Create Date: 2026-05-30 22:01:02.772185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dc121d38c8a"
down_revision: Union[str, Sequence[str], None] = "153d06e5a6a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_sessions",
        sa.Column("reset_password_token_hash", sa.String(), nullable=True),
    )
    op.add_column(
        "users_sessions",
        sa.Column(
            "reset_password_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_sessions", "reset_password_token_hash")
    op.drop_column("users_sessions", "reset_password_token_expires_at")
    # ### end Alembic commands ###
