"""Create users_sessions table

Revision ID: 43a26de5c85b
Revises: 9a28b1eacfd1
Create Date: 2026-05-14 11:27:16.156629

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43a26de5c85b"
down_revision: Union[str, Sequence[str], None] = "9a28b1eacfd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_sessions",
        sa.Column(
            "id", sa.INTEGER(), primary_key=True, autoincrement=True, nullable=False
        ),
        sa.Column(
            "user_id",
            sa.INTEGER(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column(
            "access_token_version",
            sa.INTEGER(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column("refresh_token_hash", sa.String(), nullable=True),
        sa.Column(
            "refresh_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("refresh_token_family", sa.String(64), nullable=True),
        sa.Column(
            "failed_login_attempts",
            sa.INTEGER(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_sessions")
    # ### end Alembic commands ###
