"""add inventory_id field to loans table

Revision ID: 4d7bbc3eaed7
Revises: eaa6bf9c444d
Create Date: 2026-04-28 11:50:02.077874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7bbc3eaed7'
down_revision: Union[str, Sequence[str], None] = 'eaa6bf9c444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('inventory_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'loans', 'inventories', ['inventory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'inventory_id')
    # ### end Alembic commands ###
