"""Create users_activation table

Revision ID: 5c361397e731
Revises: 43a26de5c85b
Create Date: 2026-05-14 11:42:02.972648

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c361397e731"
down_revision: Union[str, Sequence[str], None] = "43a26de5c85b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_activation",
        sa.Column(
            "id", sa.INTEGER(), primary_key=True, autoincrement=True, nullable=False
        ),
        sa.Column(
            "user_id",
            sa.INTEGER(),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("invite_token_hash", sa.String(), nullable=True),
        sa.Column("invite_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("account_activation_code_hash", sa.String(), nullable=True),
        sa.Column(
            "account_activation_code_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_activation")
    # ### end Alembic commands ###
