"""Create unique constraint for user_id column in users_sessions table

Revision ID: 7ca79e8e1a5c
Revises: 5c361397e731
Create Date: 2026-05-14 17:19:59.722564

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ca79e8e1a5c"
down_revision: Union[str, Sequence[str], None] = "5c361397e731"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_users_sessions_user_id",
        "users_sessions",
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_sessions_user_id",
        "users_sessions",
        ["user_id"],
    )
    # ### end Alembic commands ###
