"""create_pending_emails_table

Revision ID: aca7199476cd
Revises: cb29eb887844
Create Date: 2026-05-31 21:28:35.146907

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aca7199476cd'
down_revision: Union[str, Sequence[str], None] = 'cb29eb887844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_emails',
    sa.Column('recipient', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('email_type', sa.Enum('invite', 'password_reset_admin', 'activation_with_token', name='emailtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='emailsendingstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_emails_recipient_user_id'), 'pending_emails', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_pending_emails_status'), 'pending_emails', ['status'], unique=False)
    op.create_index(op.f('ix_pending_emails_triggered_by'), 'pending_emails', ['triggered_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_emails_triggered_by'), table_name='pending_emails')
    op.drop_index(op.f('ix_pending_emails_status'), table_name='pending_emails')
    op.drop_index(op.f('ix_pending_emails_recipient_user_id'), table_name='pending_emails')
    op.drop_table('pending_emails')
    # ### end Alembic commands ###
