"""Rename inventory model added_at to created_at

Revision ID: cd753ce2681a
Revises: 4d7bbc3eaed7
Create Date: 2026-05-11 14:22:32.337377

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd753ce2681a"
down_revision: Union[str, Sequence[str], None] = "4d7bbc3eaed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventories",
        "added_at",
        new_column_name="created_at",
    )
    op.alter_column(
        "loans",
        "loaned_at",
        new_column_name="created_at",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventories",
        "created_at",
        new_column_name="added_at",
    )
    op.alter_column(
        "loans",
        "created_at",
        new_column_name="loaned_at",
    )
    # ### end Alembic commands ###
