"""Create unique constraint for user_id column in users_activation table

Revision ID: e2698c73d67c
Revises: 7ca79e8e1a5c
Create Date: 2026-05-14 17:23:58.114715

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2698c73d67c'
down_revision: Union[str, Sequence[str], None] = '7ca79e8e1a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_users_activation_user_id",
        "users_activation",
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_activation_user_id",
        "users_activation",
        ["user_id"],
    )
    # ### end Alembic commands ###